POST localhost:8888/todo
Content-Type: application/json

{}

###

POST localhost:8888/todo
Content-Type: application/json

{
  "content": "퇴근하기",
  "isComplete": false
}

###

POST localhost:8888/todo
Content-Type: application/json

{
  "content": "저녁 먹기",
  "isComplete": true
}

###

GET localhost:8888/todo/1

###

GET localhost:8888/todo

###

GET localhost:8888/todo?isComplete=true

###

GET localhost:8888/todo?isComplete=false

###

PUT localhost:8888/todo/1
Content-Type: application/json

{
  "content": "퇴근하기",
  "isComplete": true
}

###

PUT localhost:8888/todo/2
Content-Type: application/json

{
  "content": "저녁 먹기",
  "isComplete": false
}

###

DELETE localhost:8888/todo

###

DELETE localhost:8888/todo?isComplete=true

###

DELETE localhost:8888/todo?isComplete=false

###

DELETE localhost:8888/todo/1

###