version: '3'
services:
  jaeger-for-test:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"
      - "14268:14268"
      - "14250:14250"
    environment:
      - LOG_LEVEL=debug
